service: grilled-cheese-snadwitch

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: src.handler.hello

plugins:
  - serverless-python-requirements
  - iam-roles-per-function
